CREATE TABLE IF NOT EXISTS KEYTYPE (
	KEYTYPEID INTEGER PRIMARY KEY NOT NULL,
	KEYTYPENAME VARCHAR(20)
)
CREATE TABLE IF NOT EXISTS KEY (
	KEYID BIGSERIAL NOT NULL PRIMARY KEY,
	KEYTYPEID INTEGER NOT NULL REFERENCES KEYTYPE (KEYTYPEID)
)
CREATE TABLE IF NOT EXISTS KEYPAIR (
	PRIVATEKEYID BIGINT NOT NULL REFERENCES KEY (KEYID),
	PUBLICKEYID BIGINT NOT NULL REFERENCES KEY (KEYID)
)
CREATE TABLE IF NOT EXISTS USERENTRY (
	USERENTRYID BIGINT NOT NULL,
	PUBLICKEYID BIGINT NOT NULL REFERENCES KEY (KEYID)
)
